interface MoveAction {
  type: 'skate' | 'pass' | 'shoot' | 'backward';
  to?: [number, number];
  targetId?: string;
  speed?: 'fast' | 'normal' | 'slow';
  group: number;
}

interface Move {
  objectId: string;
  actions: MoveAction[];
}

interface ValidationResult {
  moves: Move[];
  warnings: string[];
}

function clamp(v: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, v));
}

export function validateAndSanitizeMoves(raw: string, validObjectIds: string[]): ValidationResult {
  const warnings: string[] = [];
  const validIds = new Set(validObjectIds);

  // Strip markdown code fences
  let cleaned = raw.trim();
  const fenceMatch = cleaned.match(/```(?:json)?\s*\n?([\s\S]*?)\n?\s*```/);
  if (fenceMatch) {
    cleaned = fenceMatch[1].trim();
  }

  // Find JSON object
  if (!cleaned.startsWith('{')) {
    const start = cleaned.indexOf('{');
    if (start === -1) throw new Error('No JSON object found in AI response');
    cleaned = cleaned.slice(start);
  }

  let parsed: any;
  try {
    parsed = JSON.parse(cleaned);
  } catch {
    const lastBrace = cleaned.lastIndexOf('}');
    if (lastBrace > 0) {
      try {
        parsed = JSON.parse(cleaned.slice(0, lastBrace + 1));
      } catch {
        throw new Error('Failed to parse JSON from AI response');
      }
    } else {
      throw new Error('Failed to parse JSON from AI response');
    }
  }

  if (!parsed.moves || !Array.isArray(parsed.moves)) {
    throw new Error('Missing "moves" array in AI response');
  }

  const validTypes = new Set(['skate', 'pass', 'shoot', 'backward']);
  const validSpeeds = new Set(['fast', 'normal', 'slow']);
  const moves: Move[] = [];

  for (const move of parsed.moves) {
    if (!move.objectId || !validIds.has(move.objectId)) {
      warnings.push(`Object "${move.objectId}" not found on board — skipped`);
      continue;
    }

    if (!Array.isArray(move.actions)) continue;

    const sanitizedActions: MoveAction[] = [];
    for (const action of move.actions) {
      if (!validTypes.has(action.type)) {
        warnings.push(`Invalid action type "${action.type}" for ${move.objectId} — skipped`);
        continue;
      }

      // Clamp coordinates
      if (action.to && Array.isArray(action.to) && action.to.length >= 2) {
        action.to = [
          clamp(Number(action.to[0]) || 0, -100, 100),
          clamp(Number(action.to[1]) || 0, -42.5, 42.5),
        ];
      }

      // Validate targetId for pass/shoot
      if ((action.type === 'pass' || action.type === 'shoot') && action.targetId) {
        if (!validIds.has(action.targetId)) {
          warnings.push(`Target "${action.targetId}" not found for ${action.type} — skipped`);
          continue;
        }
      }

      // Default speed
      if (!action.speed || !validSpeeds.has(action.speed)) {
        action.speed = 'normal';
      }

      // Default group
      if (typeof action.group !== 'number' || action.group < 1) {
        action.group = 1;
      }

      sanitizedActions.push({
        type: action.type as MoveAction['type'],
        to: action.to,
        targetId: action.targetId,
        speed: (action.speed || 'normal') as MoveAction['speed'],
        group: action.group,
      });
    }

    if (sanitizedActions.length > 0) {
      moves.push({ objectId: move.objectId, actions: sanitizedActions });
    }
  }

  if (moves.length === 0) {
    throw new Error('No valid moves generated by AI');
  }

  return { moves, warnings };
}
